name: build

on: [push, pull_request]

jobs:

  linux:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    strategy:
      matrix:
        compiler: [g++, clang++]

    steps:
    - uses: actions/checkout@v1
    - name: Create build folder
      run: |
        mkdir -p build    
    - name: Compile tests
      working-directory: build
      env:
        CXX: ${{ matrix.compiler }}
      run: |
        cmake ..
        make -j4
    - name: Run tests
      working-directory: build
      run: ./uvw_static_lib_client

  windows:
    timeout-minutes: 60
    runs-on: windows-latest

    strategy:
      matrix:
        generator: [Visual Studio 17 2022]

    steps:
    - uses: actions/checkout@v1
    - name: Create build folder
      run: |
        mkdir -p build    
    - name: Compile tests
      working-directory: build
      run: |
        cmake -DCMAKE_CXX_FLAGS=/W1 -G"${{ matrix.generator }}" ..
        cmake --build . -j 4

  macos:
    timeout-minutes: 60
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: Create build folder
      run: |
        mkdir -p build
    - name: Compile tests
      working-directory: build
      run: |
        cmake  ..
        make -j4
